[project]
name = "website-data-cleaning"
version = "0.1.0"
description = "Port of legacy TJI data processing"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aws-lambda-powertools>=3.23.0",
    "boto3>=1.42.0",
    "google-api-python-client>=2.187.0",
    "google-auth-httplib2>=0.2.1",
    "google-auth-oauthlib>=1.2.3",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
]
